language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
env:
 - DJANGO_VERSION_MIN=2.2 DJANGO_VERSION_MAX=3.0
 - DJANGO_VERSION_MIN=3.0.3 DJANGO_VERSION_MAX=4.0
install:
 - pip install "django>=$DJANGO_VERSION_MIN,<$DJANGO_VERSION_MAX"
 - "pip install -e ."
 - "pip install coverage coveralls"
script:
 - "coverage run --source='django_prbac' `which django-admin.py` test django_prbac --settings django_prbac.mock_settings --traceback"
after_success:
 - coverage report
 - coveralls

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO_VERSION_MIN=3.0.3 DJANGO_VERSION_MAX=4.0
