version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  cache:
    image: redis:6-alpine
    ports:
      - 6379:6379
