# Generated by Django 2.2.24 on 2021-09-30 18:58

from django.db import migrations
try:
    from django.db.models import JSONField
except (ImportError, AttributeError):
    from django_jsonfield_backport.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('django_prbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='assignment',
            field=JSONField(blank=True, default=dict, help_text='Assignment from parameters (strings) to values (any JSON-compatible value)'),
        ),
    ]
