# Generated by Django 2.2.24 on 2021-10-04 11:33

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('django_prbac', '0002_auto_20210930_1858'),
    ]

    operations = [
        BtreeGinExtension()
    ]
