# Generated by Django 2.2.24 on 2021-10-04 11:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_prbac', '0003_auto_20211004_1133'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['assignment'], name='django_prba_assignm_471ffc_gin'),
        ),
    ]
